// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hostinput.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hostinput.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace HostBuffers {

void protobuf_ShutdownFile_hostinput_2eproto() {
  delete HostMessage::default_instance_;
  delete Instruction::default_instance_;
  delete HostBytes::default_instance_;
  delete ResizeMessage::default_instance_;
  delete EchoAck::default_instance_;
}

void protobuf_AddDesc_hostinput_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  HostMessage::default_instance_ = new HostMessage();
  Instruction::default_instance_ = new Instruction();
  HostBytes::default_instance_ = new HostBytes();
  ResizeMessage::default_instance_ = new ResizeMessage();
  EchoAck::default_instance_ = new EchoAck();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::HostBuffers::Instruction::default_instance(),
    2, 11, false, false,
    &::HostBuffers::HostBytes::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::HostBuffers::Instruction::default_instance(),
    3, 11, false, false,
    &::HostBuffers::ResizeMessage::default_instance());
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::HostBuffers::Instruction::default_instance(),
    7, 11, false, false,
    &::HostBuffers::EchoAck::default_instance());
  HostMessage::default_instance_->InitAsDefaultInstance();
  Instruction::default_instance_->InitAsDefaultInstance();
  HostBytes::default_instance_->InitAsDefaultInstance();
  ResizeMessage::default_instance_->InitAsDefaultInstance();
  EchoAck::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_hostinput_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_hostinput_2eproto {
  StaticDescriptorInitializer_hostinput_2eproto() {
    protobuf_AddDesc_hostinput_2eproto();
  }
} static_descriptor_initializer_hostinput_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int HostMessage::kInstructionFieldNumber;
#endif  // !_MSC_VER

HostMessage::HostMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HostBuffers.HostMessage)
}

void HostMessage::InitAsDefaultInstance() {
}

HostMessage::HostMessage(const HostMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HostBuffers.HostMessage)
}

void HostMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HostMessage::~HostMessage() {
  // @@protoc_insertion_point(destructor:HostBuffers.HostMessage)
  SharedDtor();
}

void HostMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HostMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const HostMessage& HostMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hostinput_2eproto();
  return *default_instance_;
}

HostMessage* HostMessage::default_instance_ = NULL;

HostMessage* HostMessage::New() const {
  return new HostMessage;
}

void HostMessage::Clear() {
  instruction_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool HostMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:HostBuffers.HostMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .HostBuffers.Instruction instruction = 1;
      case 1: {
        if (tag == 10) {
         parse_instruction:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_instruction()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_instruction;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HostBuffers.HostMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HostBuffers.HostMessage)
  return false;
#undef DO_
}

void HostMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HostBuffers.HostMessage)
  // repeated .HostBuffers.Instruction instruction = 1;
  for (int i = 0; i < this->instruction_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->instruction(i), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:HostBuffers.HostMessage)
}

int HostMessage::ByteSize() const {
  int total_size = 0;

  // repeated .HostBuffers.Instruction instruction = 1;
  total_size += 1 * this->instruction_size();
  for (int i = 0; i < this->instruction_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->instruction(i));
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HostMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const HostMessage*>(&from));
}

void HostMessage::MergeFrom(const HostMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  instruction_.MergeFrom(from.instruction_);
  mutable_unknown_fields()->append(from.unknown_fields());
}

void HostMessage::CopyFrom(const HostMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HostMessage::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->instruction())) return false;
  return true;
}

void HostMessage::Swap(HostMessage* other) {
  if (other != this) {
    instruction_.Swap(&other->instruction_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string HostMessage::GetTypeName() const {
  return "HostBuffers.HostMessage";
}


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

Instruction::Instruction()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HostBuffers.Instruction)
}

void Instruction::InitAsDefaultInstance() {
}

Instruction::Instruction(const Instruction& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HostBuffers.Instruction)
}

void Instruction::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Instruction::~Instruction() {
  // @@protoc_insertion_point(destructor:HostBuffers.Instruction)
  SharedDtor();
}

void Instruction::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Instruction::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const Instruction& Instruction::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hostinput_2eproto();
  return *default_instance_;
}

Instruction* Instruction::default_instance_ = NULL;

Instruction* Instruction::New() const {
  return new Instruction;
}

void Instruction::Clear() {
  _extensions_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool Instruction::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:HostBuffers.Instruction)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    if ((16u <= tag)) {
      DO_(_extensions_.ParseField(tag, input, default_instance_,
                                  &unknown_fields_stream));
      continue;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(
        input, tag, &unknown_fields_stream));
  }
success:
  // @@protoc_insertion_point(parse_success:HostBuffers.Instruction)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HostBuffers.Instruction)
  return false;
#undef DO_
}

void Instruction::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HostBuffers.Instruction)
  // Extension range [2, 536870912)
  _extensions_.SerializeWithCachedSizes(
      2, 536870912, output);

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:HostBuffers.Instruction)
}

int Instruction::ByteSize() const {
  int total_size = 0;

  total_size += _extensions_.ByteSize();

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Instruction::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const Instruction*>(&from));
}

void Instruction::MergeFrom(const Instruction& from) {
  GOOGLE_CHECK_NE(&from, this);
  _extensions_.MergeFrom(from._extensions_);
  mutable_unknown_fields()->append(from.unknown_fields());
}

void Instruction::CopyFrom(const Instruction& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Instruction::IsInitialized() const {


  if (!_extensions_.IsInitialized()) return false;  return true;
}

void Instruction::Swap(Instruction* other) {
  if (other != this) {
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
    _extensions_.Swap(&other->_extensions_);
  }
}

::std::string Instruction::GetTypeName() const {
  return "HostBuffers.Instruction";
}


// ===================================================================

#ifndef _MSC_VER
const int HostBytes::kHoststringFieldNumber;
#endif  // !_MSC_VER

HostBytes::HostBytes()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HostBuffers.HostBytes)
}

void HostBytes::InitAsDefaultInstance() {
}

HostBytes::HostBytes(const HostBytes& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HostBuffers.HostBytes)
}

void HostBytes::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  hoststring_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HostBytes::~HostBytes() {
  // @@protoc_insertion_point(destructor:HostBuffers.HostBytes)
  SharedDtor();
}

void HostBytes::SharedDtor() {
  if (hoststring_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete hoststring_;
  }
  if (this != default_instance_) {
  }
}

void HostBytes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const HostBytes& HostBytes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hostinput_2eproto();
  return *default_instance_;
}

HostBytes* HostBytes::default_instance_ = NULL;

HostBytes* HostBytes::New() const {
  return new HostBytes;
}

void HostBytes::Clear() {
  if (has_hoststring()) {
    if (hoststring_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      hoststring_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool HostBytes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:HostBuffers.HostBytes)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes hoststring = 4;
      case 4: {
        if (tag == 34) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_hoststring()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HostBuffers.HostBytes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HostBuffers.HostBytes)
  return false;
#undef DO_
}

void HostBytes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HostBuffers.HostBytes)
  // optional bytes hoststring = 4;
  if (has_hoststring()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->hoststring(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:HostBuffers.HostBytes)
}

int HostBytes::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes hoststring = 4;
    if (has_hoststring()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->hoststring());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HostBytes::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const HostBytes*>(&from));
}

void HostBytes::MergeFrom(const HostBytes& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_hoststring()) {
      set_hoststring(from.hoststring());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void HostBytes::CopyFrom(const HostBytes& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HostBytes::IsInitialized() const {

  return true;
}

void HostBytes::Swap(HostBytes* other) {
  if (other != this) {
    std::swap(hoststring_, other->hoststring_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string HostBytes::GetTypeName() const {
  return "HostBuffers.HostBytes";
}


// ===================================================================

#ifndef _MSC_VER
const int ResizeMessage::kWidthFieldNumber;
const int ResizeMessage::kHeightFieldNumber;
#endif  // !_MSC_VER

ResizeMessage::ResizeMessage()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HostBuffers.ResizeMessage)
}

void ResizeMessage::InitAsDefaultInstance() {
}

ResizeMessage::ResizeMessage(const ResizeMessage& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HostBuffers.ResizeMessage)
}

void ResizeMessage::SharedCtor() {
  _cached_size_ = 0;
  width_ = 0;
  height_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ResizeMessage::~ResizeMessage() {
  // @@protoc_insertion_point(destructor:HostBuffers.ResizeMessage)
  SharedDtor();
}

void ResizeMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ResizeMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ResizeMessage& ResizeMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hostinput_2eproto();
  return *default_instance_;
}

ResizeMessage* ResizeMessage::default_instance_ = NULL;

ResizeMessage* ResizeMessage::New() const {
  return new ResizeMessage;
}

void ResizeMessage::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ResizeMessage*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(width_, height_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool ResizeMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:HostBuffers.ResizeMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 width = 5;
      case 5: {
        if (tag == 40) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_height;
        break;
      }

      // optional int32 height = 6;
      case 6: {
        if (tag == 48) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HostBuffers.ResizeMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HostBuffers.ResizeMessage)
  return false;
#undef DO_
}

void ResizeMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HostBuffers.ResizeMessage)
  // optional int32 width = 5;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->width(), output);
  }

  // optional int32 height = 6;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->height(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:HostBuffers.ResizeMessage)
}

int ResizeMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 width = 5;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->width());
    }

    // optional int32 height = 6;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->height());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResizeMessage::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ResizeMessage*>(&from));
}

void ResizeMessage::MergeFrom(const ResizeMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void ResizeMessage::CopyFrom(const ResizeMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResizeMessage::IsInitialized() const {

  return true;
}

void ResizeMessage::Swap(ResizeMessage* other) {
  if (other != this) {
    std::swap(width_, other->width_);
    std::swap(height_, other->height_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ResizeMessage::GetTypeName() const {
  return "HostBuffers.ResizeMessage";
}


// ===================================================================

#ifndef _MSC_VER
const int EchoAck::kEchoAckNumFieldNumber;
#endif  // !_MSC_VER

EchoAck::EchoAck()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HostBuffers.EchoAck)
}

void EchoAck::InitAsDefaultInstance() {
}

EchoAck::EchoAck(const EchoAck& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HostBuffers.EchoAck)
}

void EchoAck::SharedCtor() {
  _cached_size_ = 0;
  echo_ack_num_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

EchoAck::~EchoAck() {
  // @@protoc_insertion_point(destructor:HostBuffers.EchoAck)
  SharedDtor();
}

void EchoAck::SharedDtor() {
  if (this != default_instance_) {
  }
}

void EchoAck::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const EchoAck& EchoAck::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hostinput_2eproto();
  return *default_instance_;
}

EchoAck* EchoAck::default_instance_ = NULL;

EchoAck* EchoAck::New() const {
  return new EchoAck;
}

void EchoAck::Clear() {
  echo_ack_num_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool EchoAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:HostBuffers.EchoAck)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 echo_ack_num = 8;
      case 8: {
        if (tag == 64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &echo_ack_num_)));
          set_has_echo_ack_num();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HostBuffers.EchoAck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HostBuffers.EchoAck)
  return false;
#undef DO_
}

void EchoAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HostBuffers.EchoAck)
  // optional uint64 echo_ack_num = 8;
  if (has_echo_ack_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(8, this->echo_ack_num(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:HostBuffers.EchoAck)
}

int EchoAck::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint64 echo_ack_num = 8;
    if (has_echo_ack_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->echo_ack_num());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EchoAck::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const EchoAck*>(&from));
}

void EchoAck::MergeFrom(const EchoAck& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_echo_ack_num()) {
      set_echo_ack_num(from.echo_ack_num());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void EchoAck::CopyFrom(const EchoAck& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EchoAck::IsInitialized() const {

  return true;
}

void EchoAck::Swap(EchoAck* other) {
  if (other != this) {
    std::swap(echo_ack_num_, other->echo_ack_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string EchoAck::GetTypeName() const {
  return "HostBuffers.EchoAck";
}

::google::protobuf::internal::ExtensionIdentifier< ::HostBuffers::Instruction,
    ::google::protobuf::internal::MessageTypeTraits< ::HostBuffers::HostBytes >, 11, false >
  hostbytes(kHostbytesFieldNumber, ::HostBuffers::HostBytes::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::HostBuffers::Instruction,
    ::google::protobuf::internal::MessageTypeTraits< ::HostBuffers::ResizeMessage >, 11, false >
  resize(kResizeFieldNumber, ::HostBuffers::ResizeMessage::default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::HostBuffers::Instruction,
    ::google::protobuf::internal::MessageTypeTraits< ::HostBuffers::EchoAck >, 11, false >
  echoack(kEchoackFieldNumber, ::HostBuffers::EchoAck::default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace HostBuffers

// @@protoc_insertion_point(global_scope)
