// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinput.proto

#ifndef PROTOBUF_userinput_2eproto__INCLUDED
#define PROTOBUF_userinput_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace ClientBuffers {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_userinput_2eproto();
void protobuf_AssignDesc_userinput_2eproto();
void protobuf_ShutdownFile_userinput_2eproto();

class UserMessage;
class Instruction;
class Keystroke;
class ResizeMessage;

// ===================================================================

class UserMessage : public ::google::protobuf::MessageLite {
 public:
  UserMessage();
  virtual ~UserMessage();

  UserMessage(const UserMessage& from);

  inline UserMessage& operator=(const UserMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const UserMessage& default_instance();

  void Swap(UserMessage* other);

  // implements Message ----------------------------------------------

  UserMessage* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const UserMessage& from);
  void MergeFrom(const UserMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ClientBuffers.Instruction instruction = 1;
  inline int instruction_size() const;
  inline void clear_instruction();
  static const int kInstructionFieldNumber = 1;
  inline const ::ClientBuffers::Instruction& instruction(int index) const;
  inline ::ClientBuffers::Instruction* mutable_instruction(int index);
  inline ::ClientBuffers::Instruction* add_instruction();
  inline const ::google::protobuf::RepeatedPtrField< ::ClientBuffers::Instruction >&
      instruction() const;
  inline ::google::protobuf::RepeatedPtrField< ::ClientBuffers::Instruction >*
      mutable_instruction();

  // @@protoc_insertion_point(class_scope:ClientBuffers.UserMessage)
 private:

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ClientBuffers::Instruction > instruction_;
  friend void  protobuf_AddDesc_userinput_2eproto();
  friend void protobuf_AssignDesc_userinput_2eproto();
  friend void protobuf_ShutdownFile_userinput_2eproto();

  void InitAsDefaultInstance();
  static UserMessage* default_instance_;
};
// -------------------------------------------------------------------

class Instruction : public ::google::protobuf::MessageLite {
 public:
  Instruction();
  virtual ~Instruction();

  Instruction(const Instruction& from);

  inline Instruction& operator=(const Instruction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Instruction& default_instance();

  void Swap(Instruction* other);

  // implements Message ----------------------------------------------

  Instruction* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Instruction& from);
  void MergeFrom(const Instruction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(Instruction)
  // @@protoc_insertion_point(class_scope:ClientBuffers.Instruction)
 private:

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_userinput_2eproto();
  friend void protobuf_AssignDesc_userinput_2eproto();
  friend void protobuf_ShutdownFile_userinput_2eproto();

  void InitAsDefaultInstance();
  static Instruction* default_instance_;
};
// -------------------------------------------------------------------

class Keystroke : public ::google::protobuf::MessageLite {
 public:
  Keystroke();
  virtual ~Keystroke();

  Keystroke(const Keystroke& from);

  inline Keystroke& operator=(const Keystroke& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Keystroke& default_instance();

  void Swap(Keystroke* other);

  // implements Message ----------------------------------------------

  Keystroke* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Keystroke& from);
  void MergeFrom(const Keystroke& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes keys = 4;
  inline bool has_keys() const;
  inline void clear_keys();
  static const int kKeysFieldNumber = 4;
  inline const ::std::string& keys() const;
  inline void set_keys(const ::std::string& value);
  inline void set_keys(const char* value);
  inline void set_keys(const void* value, size_t size);
  inline ::std::string* mutable_keys();
  inline ::std::string* release_keys();
  inline void set_allocated_keys(::std::string* keys);

  // @@protoc_insertion_point(class_scope:ClientBuffers.Keystroke)
 private:
  inline void set_has_keys();
  inline void clear_has_keys();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* keys_;
  friend void  protobuf_AddDesc_userinput_2eproto();
  friend void protobuf_AssignDesc_userinput_2eproto();
  friend void protobuf_ShutdownFile_userinput_2eproto();

  void InitAsDefaultInstance();
  static Keystroke* default_instance_;
};
// -------------------------------------------------------------------

class ResizeMessage : public ::google::protobuf::MessageLite {
 public:
  ResizeMessage();
  virtual ~ResizeMessage();

  ResizeMessage(const ResizeMessage& from);

  inline ResizeMessage& operator=(const ResizeMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ResizeMessage& default_instance();

  void Swap(ResizeMessage* other);

  // implements Message ----------------------------------------------

  ResizeMessage* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const ResizeMessage& from);
  void MergeFrom(const ResizeMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 width = 5;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 5;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 height = 6;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 6;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientBuffers.ResizeMessage)
 private:
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  friend void  protobuf_AddDesc_userinput_2eproto();
  friend void protobuf_AssignDesc_userinput_2eproto();
  friend void protobuf_ShutdownFile_userinput_2eproto();

  void InitAsDefaultInstance();
  static ResizeMessage* default_instance_;
};
// ===================================================================

static const int kKeystrokeFieldNumber = 2;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ClientBuffers::Instruction,
    ::google::protobuf::internal::MessageTypeTraits< ::ClientBuffers::Keystroke >, 11, false >
  keystroke;
static const int kResizeFieldNumber = 3;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ClientBuffers::Instruction,
    ::google::protobuf::internal::MessageTypeTraits< ::ClientBuffers::ResizeMessage >, 11, false >
  resize;

// ===================================================================

// UserMessage

// repeated .ClientBuffers.Instruction instruction = 1;
inline int UserMessage::instruction_size() const {
  return instruction_.size();
}
inline void UserMessage::clear_instruction() {
  instruction_.Clear();
}
inline const ::ClientBuffers::Instruction& UserMessage::instruction(int index) const {
  // @@protoc_insertion_point(field_get:ClientBuffers.UserMessage.instruction)
  return instruction_.Get(index);
}
inline ::ClientBuffers::Instruction* UserMessage::mutable_instruction(int index) {
  // @@protoc_insertion_point(field_mutable:ClientBuffers.UserMessage.instruction)
  return instruction_.Mutable(index);
}
inline ::ClientBuffers::Instruction* UserMessage::add_instruction() {
  // @@protoc_insertion_point(field_add:ClientBuffers.UserMessage.instruction)
  return instruction_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ClientBuffers::Instruction >&
UserMessage::instruction() const {
  // @@protoc_insertion_point(field_list:ClientBuffers.UserMessage.instruction)
  return instruction_;
}
inline ::google::protobuf::RepeatedPtrField< ::ClientBuffers::Instruction >*
UserMessage::mutable_instruction() {
  // @@protoc_insertion_point(field_mutable_list:ClientBuffers.UserMessage.instruction)
  return &instruction_;
}

// -------------------------------------------------------------------

// Instruction

// -------------------------------------------------------------------

// Keystroke

// optional bytes keys = 4;
inline bool Keystroke::has_keys() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Keystroke::set_has_keys() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Keystroke::clear_has_keys() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Keystroke::clear_keys() {
  if (keys_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    keys_->clear();
  }
  clear_has_keys();
}
inline const ::std::string& Keystroke::keys() const {
  // @@protoc_insertion_point(field_get:ClientBuffers.Keystroke.keys)
  return *keys_;
}
inline void Keystroke::set_keys(const ::std::string& value) {
  set_has_keys();
  if (keys_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    keys_ = new ::std::string;
  }
  keys_->assign(value);
  // @@protoc_insertion_point(field_set:ClientBuffers.Keystroke.keys)
}
inline void Keystroke::set_keys(const char* value) {
  set_has_keys();
  if (keys_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    keys_ = new ::std::string;
  }
  keys_->assign(value);
  // @@protoc_insertion_point(field_set_char:ClientBuffers.Keystroke.keys)
}
inline void Keystroke::set_keys(const void* value, size_t size) {
  set_has_keys();
  if (keys_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    keys_ = new ::std::string;
  }
  keys_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ClientBuffers.Keystroke.keys)
}
inline ::std::string* Keystroke::mutable_keys() {
  set_has_keys();
  if (keys_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    keys_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ClientBuffers.Keystroke.keys)
  return keys_;
}
inline ::std::string* Keystroke::release_keys() {
  clear_has_keys();
  if (keys_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = keys_;
    keys_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Keystroke::set_allocated_keys(::std::string* keys) {
  if (keys_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete keys_;
  }
  if (keys) {
    set_has_keys();
    keys_ = keys;
  } else {
    clear_has_keys();
    keys_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientBuffers.Keystroke.keys)
}

// -------------------------------------------------------------------

// ResizeMessage

// optional int32 width = 5;
inline bool ResizeMessage::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResizeMessage::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResizeMessage::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResizeMessage::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 ResizeMessage::width() const {
  // @@protoc_insertion_point(field_get:ClientBuffers.ResizeMessage.width)
  return width_;
}
inline void ResizeMessage::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:ClientBuffers.ResizeMessage.width)
}

// optional int32 height = 6;
inline bool ResizeMessage::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResizeMessage::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResizeMessage::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResizeMessage::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 ResizeMessage::height() const {
  // @@protoc_insertion_point(field_get:ClientBuffers.ResizeMessage.height)
  return height_;
}
inline void ResizeMessage::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:ClientBuffers.ResizeMessage.height)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ClientBuffers

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_userinput_2eproto__INCLUDED
